apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gallardo-art
  namespace: argocd
spec:
  project: clients
  source:
    repoURL: 'git@github.com:ArmandoGilBonet/axis-apps.git'
    targetRevision: HEAD
    path: charts/axis-wordpress
    helm:
      values: |
        namespace: client-gallardo-art
        database:
          user: gallardo
          name: gallardo
        ingress:
          host: gallardo-art.es
          tlsSecretName: gallardo-art-tls
          certManagerIssuer: axis-dns-issuer
        persistence:
          wpSize: 4Gi
          dbSize: 5Gi
        backup:
          enabled: true
          pitr:
            enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: client-gallardo-art
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true