apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ArmandoGilBonet/axis-apps.git'
    targetRevision: HEAD
    path: charts/minecraft
    helm:
      helm:
      values: |
        mc:
          gamemode: "survival"
          difficulty: "easy"
          serverName: "Servidor de Armando (Axis)"
        persistence:
          storageClass: "longhorn"
          size: 5Gi
        service:
          type: NodePort
        namespace: minecraft
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true