apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mercecastane-wp
  namespace: argocd
spec:
  project: clients
  source:
    repoURL: 'git@github.com:ArmandoGilBonet/axis-apps.git'
    targetRevision: HEAD
    path: charts/axis-wordpress
    helm:
      values: |
        namespace: client-mercecastane
        database:
          user: mercecastane
          name: mercecastane
          host: "mercecastane-db"
          tablePrefix: "qeflkj_"
          existingSecret: "mercecastane-wp-secrets"
          passwordKey: "mysql-password"
        ingress:
          host: mercecastane.es
          tlsSecretName: mercecastane-tls
          certManagerIssuer: axis-dns-issuer
        persistence:
          wpSize: 4Gi
          dbSize: 5Gi
          storageClass: longhorn
        backup:
          enabled: true
          plan: "silver"
          bucketFull: "axis-mariadb-backup-789ddgum3nz4cz645bgo"
          bucketExports: "axis-mariadb-exports-2jjj4f3i07p7kme6idd2"
          s3Endpoint: "s3.eu-west-1.amazonaws.com"
          region: "eu-west-1"
          schedule: "* */4 * * *"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: client-mercecastane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false