apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-s3-infra-creds # Este es el nombre local en el namespace 'automation'
  namespace: automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: axis-aws-store
    kind: ClusterSecretStore # <--- Esto es vital
  target:
    name: aws-s3-infra-creds
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: axis-aws-s3-infra-backup-creds # El nombre del SealedSecret en external-secrets
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: axis-aws-s3-infra-backup-creds
      property: AWS_SECRET_ACCESS_KEY