apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-s3-infra-creds
  namespace: automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: axis-aws-store # Asegúrate de que este Store usa el SealedSecret que me has pasado
    kind: SecretStore
  target:
    name: aws-s3-infra-creds # Este es el nombre del Secret que buscarán los Pods
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: axis-aws-s3-infra-backup-creds # La key dentro de tu proveedor/secret
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: axis-aws-s3-infra-backup-creds
        property: AWS_SECRET_ACCESS_KEY