apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-postgres
  namespace: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-postgres
  template:
    metadata:
      labels:
        app: n8n-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: "n8n_admin"
            - name: POSTGRES_PASSWORD
              value: "axis_automation_pwd"
            - name: POSTGRES_DB
              value: "n8n_db"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-infra-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-infra-creds
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata # Evita problemas con la carpeta lost+found en el PVC
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-n8n-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: automation
spec:
  replicas: 1
  strategy:
    type: Recreate # Importante para que no choquen al intentar montar el mismo PVC
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          env:
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "https"
            - name: WEBHOOK_URL
              value: "https://n8n.armandogil.es/"
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_HOST
              value: "n8n-postgres-svc"
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: "n8n_db"
            - name: DB_POSTGRESDB_USER
              value: "n8n_admin"
            - name: DB_POSTGRESDB_PASSWORD
              value: "axis_automation_pwd"
            # Evita problemas con la carpeta lost+found en el PVC
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc