apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: automation
spec:
  instances: 1 # Empieza con 1 para la migración, luego sube a 2 o 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  
  postgresql:
    parameters:
      max_wal_size: "1GB"      # Evita que el WAL crezca indefinidamente
      min_wal_size: "512MB"
      archive_timeout: "300s"  # Fuerza el archivado cada 5 min
      checkpoint_timeout: "5min"

  # Importante para Axis: Permitir réplicas en un solo nodo (Gendo)
  affinity:
    enablePodAntiAffinity: false

  # Reutilizamos tus nombres de DB y User
  bootstrap:
    initdb:
      database: n8n_db
      owner: n8n_admin
      secret:
        name: n8n-postgres-secrets

  storage:
    size: 12Gi
    storageClass: longhorn

  # Configuración de Backup Nativo a S3
  backup:
    barmanObjectStore:
      destinationPath: s3://axis-infra-backup-v7uc1944w8g7v79irbrb/n8n-db/
      endpointURL: https://s3.eu-west-1.amazonaws.com
      s3Credentials:
        accessKeyId:
          name: aws-s3-infra-creds
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: aws-s3-infra-creds
          key: AWS_SECRET_ACCESS_KEY
      data:
        compression: gzip
        jobs: 2
      wal:
        compression: gzip
    retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: n8n-db-daily-backup
spec:
  schedule: "0 0 3 * * *" # Todos los días a las 3 AM
  cluster:
    name: n8n-db