apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mercecastane-secrets
  namespace: client-mercecastane
spec:
  encryptedData:
    mysql-password: AgBQbU3tNqchYEANaTaRlQGotSbDz4AqyIPaTxNIR5L0EXL2WAnypTPIhrcBMIpmfeOLv6McQUNcT1C8EiwDX5yHBRvVJOWL/xXbgyzTf+A/hQ8qyhK+dMl9Ulc3ytcL/R/5FB6bg2+WNqKUMZ+lgLNeet1qTmomfktmq6LFiMemTHayBdVLZ5eaRLWex4hAfP/xObHBuXjM4UBjo8+sASO4haUgNoqJz1RyBht3lsbQ+JgvLBrUaaX1pXIvr/KZjvPgOd/xBrGQvQk0VTM2iywJZY9kOYViYCogo5ypOmhXBy/jLKfoTFeWuXGxgH6CGIpDAtImjvhCIT7cBHl7toMBmybHdxtvGhYtjGWozLdJRXGwnzQa6c9gVaq7d7Ds0n3iCDuGAPIzR3ARuOP+JRk6JNSftQQDdTamVebW7D/l31An9plavXguU3Zzv41fcRqODQBHsXv1L/nwzS5yVE3CvuhJZXHN/zizxIhDP8k6iw9rqfRubqlbLkWCd6R/H92QJGEhBlLeIi2zGl1/G/I+wb3vlIdQ2gzf3DkJRpu5N6ApbgowWtl+jz9FeRh0B2JKWu2/Sam8G0FATiduqHYUOnlnbtXKkHQVvIZvihf+OxF67AETfCk5MLbyHHDBt++L95uD2vf9me1hLQ/pfWHIzPWt/bC4KIUukg3Px5ZYRVBG82T1hszep21stER/vaknO3GNOGuo9KpSg6nAfRgmj+nBddzX3AxN